apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-service
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
  - port: 443
    protocol: TCP
    name: https
  - port: 22
    protocol: TCP
    name: ssh
  selector:
    app: nginx-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-service
spec:
  selector:
    matchLabels:
      app: nginx-service
  template:
    metadata:
      labels:
        app: nginx-service
    spec:
      containers:
      - name: nginx
        image: nginx-img:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
    - secretName: tls-keys
  backend:
    serviceName: nginx
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
